# Generated by Django 4.2.6 on 2023-10-27 19:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_surcharge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderdiscount",
            options={
                "ordering": ["pk"],
                "verbose_name": "Order Discount",
                "verbose_name_plural": "Order Discounts",
            },
        ),
        migrations.AlterModelOptions(
            name="ordernote",
            options={
                "ordering": ["-date_updated"],
                "verbose_name": "Order Note",
                "verbose_name_plural": "Order Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="surcharge",
            options={
                "ordering": ["pk"],
                "verbose_name": "Surcharge",
                "verbose_name_plural": "Surcharges",
            },
        ),
        migrations.RemoveField(
            model_name="line",
            name="est_dispatch_date",
        ),
        migrations.RemoveField(
            model_name="line",
            name="unit_cost_price",
        ),
        migrations.RemoveField(
            model_name="line",
            name="unit_retail_price",
        ),
        migrations.AddField(
            model_name="line",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="VAT rate code"
            ),
        ),
        migrations.AddField(
            model_name="lineprice",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="VAT rate code"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_tax_code",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Shipping VAT rate code",
            ),
        ),
        migrations.AddField(
            model_name="surcharge",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="VAT rate code"
            ),
        ),
        migrations.AlterField(
            model_name="lineattribute",
            name="value",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Value",
            ),
        ),
    ]
