version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    command: python sandbox/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - .:/code
