postgres:
  image: postgres:latest
elasticsearch:
    image: elasticsearch:1

test:
  build: .
  command: python sandbox/manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  links:
    - postgres
    - elasticsearch
  volumes:
    - .:/code
