# Generated by Django 3.0.8 on 2020-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0008_auto_20190927_1206"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Date Updated"
            ),
        ),
    ]
