# Generated by Django 4.2.6 on 2023-10-27 19:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0009_line_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="VAT rate code"
            ),
        ),
        migrations.AlterField(
            model_name="lineattribute",
            name="value",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Value",
            ),
        ),
    ]
