# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wellsfargo", "0001_squash_060"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfermetadata",
            name="credentials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers",
                to="wellsfargo.APICredentials",
                verbose_name="API Credentials",
            ),
        ),
    ]
