# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0004_auto_20170510_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingplan',
            name='fine_print_superscript',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Fine Print Superscript'),
        ),
    ]
