# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 17:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0005_auto_20160701_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingplan',
            name='plan_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1001), django.core.validators.MaxValueValidator(9999)], verbose_name='Plan Number'),  # NOQA
        ),
    ]
