# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellsfargo", "0006_financingplan_product_price_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="financingplan",
            name="advertising_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Is Advertising Enabled for Plan?"
            ),
        ),
    ]
