# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellsfargo', '0007_financingplan_allow_credit_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacreditapp',
            name='submitting_user',
            field=models.ForeignKey(blank=True, help_text='Select the user who filled out and submitted the credit application (not always the same as the user who is applying for credit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submitting User'),
        ),
        migrations.AddField(
            model_name='cajointcreditapp',
            name='submitting_user',
            field=models.ForeignKey(blank=True, help_text='Select the user who filled out and submitted the credit application (not always the same as the user who is applying for credit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submitting User'),
        ),
        migrations.AddField(
            model_name='uscreditapp',
            name='submitting_user',
            field=models.ForeignKey(blank=True, help_text='Select the user who filled out and submitted the credit application (not always the same as the user who is applying for credit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submitting User'),
        ),
        migrations.AddField(
            model_name='usjointcreditapp',
            name='submitting_user',
            field=models.ForeignKey(blank=True, help_text='Select the user who filled out and submitted the credit application (not always the same as the user who is applying for credit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submitting User'),
        ),
        migrations.AlterField(
            model_name='cacreditapp',
            name='user',
            field=models.ForeignKey(help_text='Select the user user who is applying and who will own (be the primary user of) this account.', on_delete=django.db.models.deletion.CASCADE, related_name='ca_individual_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='cajointcreditapp',
            name='user',
            field=models.ForeignKey(help_text='Select the user user who is applying and who will own (be the primary user of) this account.', on_delete=django.db.models.deletion.CASCADE, related_name='ca_joint_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='uscreditapp',
            name='user',
            field=models.ForeignKey(help_text='Select the user user who is applying and who will own (be the primary user of) this account.', on_delete=django.db.models.deletion.CASCADE, related_name='us_individual_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='usjointcreditapp',
            name='user',
            field=models.ForeignKey(help_text='Select the user user who is applying and who will own (be the primary user of) this account.', on_delete=django.db.models.deletion.CASCADE, related_name='us_joint_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
