# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellsfargo', '0008_auto_20170117_1413'),
    ]

    operations = [
        # Add fields to transfermetadata model
        migrations.AddField(
            model_name='transfermetadata',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfermetadata',
            name='merchant_reference',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transfermetadata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wfrs_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Requesting User'),
        ),
        migrations.AddField(
            model_name='transfermetadata',
            name='encrypted_account_number',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='transfermetadata',
            name='last4_account_number',
            field=models.CharField(default='', max_length=4, verbose_name='Last 4 digits of account number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfermetadata',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfermetadata',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cacreditapp',
            name='last4_account_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Resulting Account'),
        ),
        migrations.AddField(
            model_name='cajointcreditapp',
            name='last4_account_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Resulting Account'),
        ),
        migrations.AddField(
            model_name='uscreditapp',
            name='last4_account_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Resulting Account'),
        ),
        migrations.AddField(
            model_name='usjointcreditapp',
            name='last4_account_number',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Resulting Account'),
        ),
    ]
