# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0014_auto_20180222_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='prequalificationresponse',
            name='reported_datetime',
            field=models.DateTimeField(blank=True, help_text='Date customer response was reported to Wells Fargo.', null=True),
        ),
    ]
