# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('wellsfargo', '0015_prequalificationresponse_reported_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='prequalificationresponse',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prequalification_responses', to='order.Order'),
        ),
    ]
