# Generated by Django 2.1.4 on 2018-12-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellsfargo", "0021_auto_20181105_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="prequalificationrequest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="prequalificationrequest",
            name="line2",
            field=models.CharField(
                blank=True, max_length=26, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AddField(
            model_name="prequalificationrequest",
            name="middle_initial",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="Middle Initial"
            ),
        ),
        migrations.AlterField(
            model_name="prequalificationresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Pre-qualification Approved"),
                    ("D", "Pre-qualification Not Approved"),
                    ("E", "System Error"),
                    ("M", "Down for Maintenance"),
                ],
                max_length=1,
                verbose_name="Transaction Status",
            ),
        ),
    ]
