# Generated by Django 2.1.5 on 2019-02-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wellsfargo", "0024_auto_20190125_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="cacreditapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Unknown"),
                    ("E0", "Approved"),
                    ("E1", "Pending"),
                    ("E2", "Format Error"),
                    ("E3", "Wells Fargo Error"),
                    ("E4", "Denied"),
                ],
                default="",
                max_length=2,
                verbose_name="Application Status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cajointcreditapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Unknown"),
                    ("E0", "Approved"),
                    ("E1", "Pending"),
                    ("E2", "Format Error"),
                    ("E3", "Wells Fargo Error"),
                    ("E4", "Denied"),
                ],
                default="",
                max_length=2,
                verbose_name="Application Status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uscreditapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Unknown"),
                    ("E0", "Approved"),
                    ("E1", "Pending"),
                    ("E2", "Format Error"),
                    ("E3", "Wells Fargo Error"),
                    ("E4", "Denied"),
                ],
                default="",
                max_length=2,
                verbose_name="Application Status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usjointcreditapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Unknown"),
                    ("E0", "Approved"),
                    ("E1", "Pending"),
                    ("E2", "Format Error"),
                    ("E3", "Wells Fargo Error"),
                    ("E4", "Denied"),
                ],
                default="",
                max_length=2,
                verbose_name="Application Status",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transfermetadata",
            name="last4_account_number",
            field=models.CharField(
                max_length=4, verbose_name="Last 4 digits of account number"
            ),
        ),
        migrations.AddField(
            model_name="accountinquiryresult",
            name="encrypted_account_number",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="accountinquiryresult",
            name="credit_app_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountinquiryresult",
            name="credit_app_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
    ]
