# Generated by Django 2.1.5 on 2019-02-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wellsfargo", "0026_auto_20190208_1629"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cacreditapp",
            name="inquiries",
        ),
        migrations.RemoveField(
            model_name="cajointcreditapp",
            name="inquiries",
        ),
        migrations.RemoveField(
            model_name="uscreditapp",
            name="inquiries",
        ),
        migrations.RemoveField(
            model_name="usjointcreditapp",
            name="inquiries",
        ),
    ]
