# Generated by Django 2.2.11 on 2020-03-26 18:12
from django.db import migrations


def migrate_credit_app_data(apps, schema_editor):
    # Old Cedit Apps
    USCreditApp = apps.get_model('wellsfargo', 'USCreditApp')
    USJointCreditApp = apps.get_model('wellsfargo', 'USJointCreditApp')

    # New unified Credit App model
    CreditApplicationAddress = apps.get_model('wellsfargo', 'CreditApplicationAddress')
    CreditApplicationApplicant = apps.get_model('wellsfargo', 'CreditApplicationApplicant')
    CreditApplication = apps.get_model('wellsfargo', 'CreditApplication')

    # Migrate USCreditApp
    for old_app in USCreditApp.objects.all():
        main_applicant_addr = CreditApplicationAddress.objects.create(
            address_line_1=old_app.main_address_line1,
            address_line_2=old_app.main_address_line2,
            city=old_app.main_address_city,
            state_code=old_app.main_address_state,
            postal_code=old_app.main_address_postcode,
        )
        main_applicant = CreditApplicationApplicant.objects.create(
            first_name=old_app.main_first_name,
            last_name=old_app.main_last_name,
            middle_initial=old_app.main_middle_initial,
            date_of_birth=old_app.main_date_of_birth,
            ssn=old_app.main_ssn,
            annual_income=old_app.main_annual_income,
            email_address=old_app.email,
            home_phone=old_app.main_home_phone,
            mobile_phone=old_app.main_cell_phone,
            work_phone=old_app.main_employer_phone,
            employer_name=old_app.main_employer_name,
            housing_status=old_app.main_housing_status,
            address=main_applicant_addr,
        )
        new_app = CreditApplication.objects.create(
            requested_credit_limit=old_app.purchase_price,
            language_preference=old_app.language,
            salesperson=old_app.new_sales_person,
            main_applicant=main_applicant,
            joint_applicant=None,
            status=old_app.status,
            credentials=old_app.credentials,
            application_source=old_app.application_source,
            user=old_app.user,
            ip_address=old_app.ip_address,
            submitting_user=old_app.submitting_user,
            encrypted_account_number=old_app.encrypted_account_number,
            last4_account_number=old_app.last4_account_number,
            created_datetime=old_app.created_datetime,
            modified_datetime=old_app.modified_datetime,
        )
        for inquiry in old_app.inquiries.all():
            inquiry.new_credit_app = new_app
            inquiry.save()

    # Migrate USJointCreditApp
    for old_app in USJointCreditApp.objects.all():
        main_applicant_addr = CreditApplicationAddress.objects.create(
            address_line_1=old_app.main_address_line1,
            address_line_2=old_app.main_address_line2,
            city=old_app.main_address_city,
            state_code=old_app.main_address_state,
            postal_code=old_app.main_address_postcode,
        )
        main_applicant = CreditApplicationApplicant.objects.create(
            first_name=old_app.main_first_name,
            last_name=old_app.main_last_name,
            middle_initial=old_app.main_middle_initial,
            date_of_birth=old_app.main_date_of_birth,
            ssn=old_app.main_ssn,
            annual_income=old_app.main_annual_income,
            email_address=old_app.email,
            home_phone=old_app.main_home_phone,
            mobile_phone=old_app.main_cell_phone,
            work_phone=old_app.main_employer_phone,
            employer_name=old_app.main_employer_name,
            housing_status=old_app.main_housing_status,
            address=main_applicant_addr,
        )
        joint_applicant_addr = CreditApplicationAddress.objects.create(
            address_line_1=old_app.joint_address_line1,
            address_line_2=old_app.joint_address_line2,
            city=old_app.joint_address_city,
            state_code=old_app.joint_address_state,
            postal_code=old_app.joint_address_postcode,
        )
        joint_applicant = CreditApplicationApplicant.objects.create(
            first_name=old_app.joint_first_name,
            last_name=old_app.joint_last_name,
            middle_initial=old_app.joint_middle_initial,
            date_of_birth=old_app.joint_date_of_birth,
            ssn=old_app.joint_ssn,
            annual_income=old_app.joint_annual_income,
            email_address=None,
            home_phone=old_app.joint_home_phone,
            mobile_phone=old_app.joint_cell_phone,
            work_phone=old_app.joint_employer_phone,
            employer_name=old_app.joint_employer_name,
            housing_status=None,
            address=joint_applicant_addr,
        )
        new_app = CreditApplication.objects.create(
            requested_credit_limit=old_app.purchase_price,
            language_preference=old_app.language,
            salesperson=old_app.new_sales_person,
            main_applicant=main_applicant,
            joint_applicant=joint_applicant,
            status=old_app.status,
            credentials=old_app.credentials,
            application_source=old_app.application_source,
            user=old_app.user,
            ip_address=old_app.ip_address,
            submitting_user=old_app.submitting_user,
            encrypted_account_number=old_app.encrypted_account_number,
            last4_account_number=old_app.last4_account_number,
            created_datetime=old_app.created_datetime,
            modified_datetime=old_app.modified_datetime,
        )
        for inquiry in old_app.inquiries.all():
            inquiry.new_credit_app = new_app
            inquiry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0034_auto_20200326_1411'),
    ]

    operations = [
        migrations.RunPython(migrate_credit_app_data),
    ]
