# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0009_auto_20160729_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacreditapp',
            name='account',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_individual_credit_app', to='oscar_accounts.Account', verbose_name='Account'),  # NOQA
        ),
        migrations.AlterField(
            model_name='cacreditapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_individual_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),  # NOQA
        ),
        migrations.AlterField(
            model_name='cajointcreditapp',
            name='account',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_joint_credit_app', to='oscar_accounts.Account', verbose_name='Account'),  # NOQA
        ),
        migrations.AlterField(
            model_name='cajointcreditapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_joint_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),  # NOQA
        ),
        migrations.AlterField(
            model_name='financingplanbenefit',
            name='group_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uscreditapp',
            name='account',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='us_individual_credit_app', to='oscar_accounts.Account', verbose_name='Account'),  # NOQA
        ),
        migrations.AlterField(
            model_name='uscreditapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_individual_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),  # NOQA
        ),
        migrations.AlterField(
            model_name='usjointcreditapp',
            name='account',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='us_joint_credit_app', to='oscar_accounts.Account', verbose_name='Account'),  # NOQA
        ),
        migrations.AlterField(
            model_name='usjointcreditapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_joint_credit_apps', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),  # NOQA
        ),
    ]
