# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0002_auto_20160729_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingplan',
            name='is_default_plan',
            field=models.BooleanField(default=False, verbose_name='Is Default Plan?'),
        ),
    ]
