# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0006_apicredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingplan',
            name='allow_credit_application',
            field=models.BooleanField(default=True, verbose_name='Allow new credit applications when user is eligible for this plan?'),
        ),
    ]
